config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :transacs
  resources :accounts
  resources :users

   root 'sessions#new'
   get 'users/:id/dash' => 'users#dash'

  get     'login' => 'sessions#new'
  post    'login' => 'sessions#create'
  delete  'logout' => 'sessions#destroy'

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user
	has_many :transacs
	validates :rib, format: { with: /[0-9]{16,16}/ , message: "Un compte doit avoir un identifiant composé de 16 chiffres"}
	validates :rib, uniqueness: { with: true, message: ": ce numéro de compte existe déjà (l'identifiant doit être unique)"}
	validates :rib, presence: { with: true, message: ": veuillez saisir un numéro de compte"}
	validates :libelle, presence: { with: true, message: ": veuillez saisir un intitulé"}
	validates :user, presence: { with: true, message: ": veuillez associer un utilisateur à ce compte"}
end

app/models/transac.rb
class Transac < ActiveRecord::Base
	belongs_to :account
	validates :title, presence: { with: true, message: ": veuillez saisir un intitulé"}
	validates :account, presence: { with: true, message: ": veuillez associer un compte à cette transaction "}
	validates :amount, presence: { with: true, message: ": veuillez indiquer un montant"}
	validates :inout, presence: { with: true, message: ": veuillez préciser 'entrante' ou 'sortante'"}
	enum inout: [:entrante , :sortante]
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :accounts

	validates :login, presence: { with: true, message: ": veuillez saisir un login"}
	validates :pwd, presence: { with: true, message: ": veuillez saisir un mot de passe"}
	validates :sexe, inclusion: { in: ["M", "F", nil], message: "(%{value}): veuillez préciser 'M' ou 'F'"}
	enum sexe: [:"M" , :"F"]

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:rib, :libelle, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user=User.find_by(login: params[:session][:login].downcase)
  	if user && user.pwd == params[:session][:password]
      log_in user
      redirect_to user
  	else
  		flash.now[:danger] = 'Merci de ré-essayer'
	  	render 'new'
	  end
  end

  def destroy
      log_out
      redirect_to root_url
  end

private



end

app/controllers/transacs_controller.rb
class TransacsController < ApplicationController
  before_action :set_transac, only: [:show, :edit, :update, :destroy]

  # GET /transacs
  # GET /transacs.json
  def index
    @transacs = Transac.all
  end

  # GET /transacs/1
  # GET /transacs/1.json
  def show
  end

  # GET /transacs/new
  def new
    @transac = Transac.new
  end

  # GET /transacs/1/edit
  def edit
  end

  # POST /transacs
  # POST /transacs.json
  def create
    @transac = Transac.new(transac_params)

    respond_to do |format|
      if @transac.save
        format.html { redirect_to @transac, notice: 'Transac was successfully created.' }
        format.json { render :show, status: :created, location: @transac }
      else
        format.html { render :new }
        format.json { render json: @transac.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transacs/1
  # PATCH/PUT /transacs/1.json
  def update
    respond_to do |format|
      if @transac.update(transac_params)
        format.html { redirect_to @transac, notice: 'Transac was successfully updated.' }
        format.json { render :show, status: :ok, location: @transac }
      else
        format.html { render :edit }
        format.json { render json: @transac.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transacs/1
  # DELETE /transacs/1.json
  def destroy
    @transac.destroy
    respond_to do |format|
      format.html { redirect_to transacs_url, notice: 'Transac was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transac
      @transac = Transac.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transac_params
      params.require(:transac).permit(:inout, :amount, :amount, :title, :account_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @accounts=@user.accounts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1/dash
  def dash
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:login, :pwd,:nom, :prenom, :sexe, :adresse)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	

end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def log_in(user)
		session[:user_id]= user.id
	end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/transacs_helper.rb
module TransacsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/_account.html.erb
<li id="account-<%= account.id %>">
  <span class="user"><%= link_to account.rib, account %></span>
  <span class="content"><%= account.id %></span>
  <span class="content"><%= account.libelle %></span>
</li>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rib %><br>
    <%= f.text_field :rib %>
  </div>
  <div class="field">
    <%= f.label :libelle %><br>
    <%= f.text_field :libelle %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Rib</th>
      <th>Libelle</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.rib %></td>
        <td><%= account.libelle %></td>
        <td><%= account.user_id %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rib:</strong>
  <%= @account.rib %>
</p>

<p>
  <strong>Libelle:</strong>
  <%= @account.libelle %>
</p>

<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h3>Exercice NICOLAS: mini-plate-forme</h3>

<%= @current_user %>
<% if ( session[:user_id] ) %>
	<%= "(user #{session[:user_id]} : #{User.find_by(id: session[:user_id]).login})" %>
	<%= link_to 'Déconnexion', logout_url, method: :delete, data: { confirm: 'Souhaitez-vous vous déconnecter ?' } %>
<% else %>
	<%= link_to "Création d'un utilisateur", new_user_path %>
<% end %>


<%= yield %>

</body>
</html>

app/views/transacs/_form.html.erb
<%= form_for(@transac) do |f| %>
  <% if @transac.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transac.errors.count, "error") %> prohibited this transac from being saved:</h2>

      <ul>
      <% @transac.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :inout %><br>
    <%= f.text_field :inout %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :account_id %><br>
    <%= f.number_field :account_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transacs/edit.html.erb
<h1>Editing Transac</h1>

<%= render 'form' %>

<%= link_to 'Show', @transac %> |
<%= link_to 'Back', transacs_path %>

app/views/transacs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Transacs</h1>

<table>
  <thead>
    <tr>
      <th>Inout</th>
      <th>Amount</th>
      <th>Amount</th>
      <th>Title</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transacs.each do |transac| %>
      <tr>
        <td><%= transac.inout %></td>
        <td><%= transac.amount %></td>
        <td><%= transac.amount %></td>
        <td><%= transac.title %></td>
        <td><%= transac.account_id %></td>
        <td><%= link_to 'Show', transac %></td>
        <td><%= link_to 'Edit', edit_transac_path(transac) %></td>
        <td><%= link_to 'Destroy', transac, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transac', new_transac_path %>

app/views/transacs/new.html.erb
<h1>New Transac</h1>

<%= render 'form' %>

<%= link_to 'Back', transacs_path %>

app/views/transacs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inout:</strong>
  <%= @transac.inout %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transac.amount %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transac.amount %>
</p>

<p>
  <strong>Title:</strong>
  <%= @transac.title %>
</p>

<p>
  <strong>Account:</strong>
  <%= @transac.account_id %>
</p>

<%= link_to 'Edit', edit_transac_path(@transac) %> |
<%= link_to 'Back', transacs_path %>

app/views/users/_dashboard.erb
<%= User.find_by(id: session[:user_id]).nom %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6 col-md-offset-3">
    <%= f.label :login %><br>
    <%= f.text_field :login, class: 'form-control' %>

    <%= f.label :password, "Mot de passe" %><br>
    <%= f.password_field :pwd, class: 'form-control' %>

    <%= f.label :nom %><br>
    <%= f.text_field :nom, class: 'form-control' %>

    <%= f.label :prenom %><br>
    <%= f.text_field :prenom, class: 'form-control' %>

    <%= f.label :sexe %> ("M" ou "F")<br>
    <%= f.text_field :sexe, class: 'form-control' %>

    <%= f.label :adresse %><br>
    <%= f.text_field :adresse, class: 'form-control' %>

    <%= f.submit "Créer l'utilisateur", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/users/dash.erb
<h1>DashBoard</h1>


<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Login</th>
      <th>Password</th>
      <th>Sexe</th>
      <th>Adresse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nom %></td>
        <td><%= user.prenom %></td>
        <td><%= user.login %></td>
        <td><%= user.pwd %></td>
        <td><%= user.sexe %></td>
        <td><%= user.adresse %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= user.id  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Création d'un nouvel utilisateur</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="accounts">
	<%= render @accounts %>
</ul>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>
<p>
  <strong>Nom:</strong>
  <%= @user.nom %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @user.prenom %>
</p>

<p>
  <strong>Sexe:</strong>
  <%= @user.sexe %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @user.adresse %>
</p>

<%#= link_to 'Dashboard', dash_user_path(@user) %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>